// <auto-generated />
using System;
using Lib_Metier.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib_Metier.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224152647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Lib_Entities.Entities.Espace", b =>
                {
                    b.Property<int>("IdEspace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_espace");

                    b.Property<int>("CapaciteMaxi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capaciteMaxi");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<int>("Superficie")
                        .HasColumnType("INTEGER")
                        .HasColumnName("superficie");

                    b.HasKey("IdEspace");

                    b.ToTable("Espace", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Plateforme", b =>
                {
                    b.Property<int>("IdPlateforme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_plateforme");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("libelle");

                    b.HasKey("IdPlateforme");

                    b.ToTable("Plateforme", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.PosteJeu", b =>
                {
                    b.Property<int>("NumeroPoste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_poste");

                    b.Property<string>("Fonctionnel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fonctionnel");

                    b.Property<int>("IdEspace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_espace");

                    b.Property<int>("IdPlateforme")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_plateforme");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.HasKey("NumeroPoste");

                    b.HasIndex("IdEspace");

                    b.HasIndex("IdPlateforme");

                    b.ToTable("Poste_Jeu", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Tournoi", b =>
                {
                    b.Property<int>("NumeroTournoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("numeroTournoi");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT")
                        .HasColumnName("dateHeure");

                    b.Property<int>("DureePrevue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dureePrevue");

                    b.Property<int>("IdEspace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_espace");

                    b.Property<int>("NbParticipants")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nbParticipants");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("statut");

                    b.HasKey("NumeroTournoi");

                    b.HasIndex("IdEspace");

                    b.ToTable("Tournoi", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.PosteJeu", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Espace", "Espace")
                        .WithMany("PostesJeu")
                        .HasForeignKey("IdEspace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Entities.Entities.Plateforme", "Plateforme")
                        .WithMany("PostesJeu")
                        .HasForeignKey("IdPlateforme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espace");

                    b.Navigation("Plateforme");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Tournoi", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Espace", "Espace")
                        .WithMany("Tournois")
                        .HasForeignKey("IdEspace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espace");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Espace", b =>
                {
                    b.Navigation("PostesJeu");

                    b.Navigation("Tournois");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Plateforme", b =>
                {
                    b.Navigation("PostesJeu");
                });
#pragma warning restore 612, 618
        }
    }
}
