// <auto-generated />
using System;
using Lib_Metier.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib_Metier.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Lib_Entities.Entities.Espace", b =>
                {
                    b.Property<int>("IdEspace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_espace");

                    b.Property<int>("CapaciteMaxi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capaciteMaxi");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<int>("Superficie")
                        .HasColumnType("INTEGER")
                        .HasColumnName("superficie");

                    b.HasKey("IdEspace");

                    b.ToTable("Espace", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Lot", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstAttribue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estAttribue");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("libelle");

                    b.Property<int>("NumeroTournoi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numeroTournoi");

                    b.Property<int>("RangAttribution")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rangAttribution");

                    b.Property<float>("ValeurTotale")
                        .HasColumnType("REAL")
                        .HasColumnName("valeurTotale");

                    b.HasKey("Numero");

                    b.ToTable("Lot", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.LotComposant", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Description")
                        .HasColumnType("INTEGER")
                        .HasColumnName("description");

                    b.Property<int>("Libelle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("libelle");

                    b.Property<int>("NumeroLot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_lot");

                    b.Property<int>("Valeur")
                        .HasColumnType("INTEGER")
                        .HasColumnName("valeur");

                    b.HasKey("Numero");

                    b.ToTable("LotComposant", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Organisateur", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<int>("IdRole")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_role");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mail");

                    b.Property<string>("motPasse")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("motPasse");

                    b.HasKey("Login");

                    b.HasIndex("IdRole");

                    b.ToTable("Organisateur", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Plateforme", b =>
                {
                    b.Property<int>("IdPlateforme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_plateforme");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("libelle");

                    b.HasKey("IdPlateforme");

                    b.ToTable("Plateforme", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.PosteJeu", b =>
                {
                    b.Property<int>("NumeroPoste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_poste");

                    b.Property<string>("Fonctionnel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fonctionnel");

                    b.Property<int>("IdEspace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_espace");

                    b.Property<int>("IdPlateforme")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_plateforme");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.HasKey("NumeroPoste");

                    b.HasIndex("IdEspace");

                    b.HasIndex("IdPlateforme");

                    b.ToTable("Poste_Jeu", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_role");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Tournoi", b =>
                {
                    b.Property<int>("NumeroTournoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("numeroTournoi");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT")
                        .HasColumnName("dateHeure");

                    b.Property<int>("DureePrevue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dureePrevue");

                    b.Property<int>("IdEspace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_espace");

                    b.Property<int>("NbParticipants")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nbParticipants");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("statut");

                    b.HasKey("NumeroTournoi");

                    b.HasIndex("IdEspace");

                    b.ToTable("Tournoi", (string)null);
                });

            modelBuilder.Entity("Lib_Entities.Entities.Lot", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Tournoi", "Tournoi")
                        .WithMany("Lot")
                        .HasForeignKey("Numero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("Lib_Entities.Entities.LotComposant", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Lot", "Lot")
                        .WithMany("LotComposant")
                        .HasForeignKey("Numero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Organisateur", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Role", "Role")
                        .WithMany("Organisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lib_Entities.Entities.PosteJeu", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Espace", "Espace")
                        .WithMany("PostesJeu")
                        .HasForeignKey("IdEspace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Entities.Entities.Plateforme", "Plateforme")
                        .WithMany("PostesJeu")
                        .HasForeignKey("IdPlateforme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espace");

                    b.Navigation("Plateforme");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Tournoi", b =>
                {
                    b.HasOne("Lib_Entities.Entities.Espace", "Espace")
                        .WithMany("Tournois")
                        .HasForeignKey("IdEspace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espace");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Espace", b =>
                {
                    b.Navigation("PostesJeu");

                    b.Navigation("Tournois");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Lot", b =>
                {
                    b.Navigation("LotComposant");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Plateforme", b =>
                {
                    b.Navigation("PostesJeu");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Role", b =>
                {
                    b.Navigation("Organisateurs");
                });

            modelBuilder.Entity("Lib_Entities.Entities.Tournoi", b =>
                {
                    b.Navigation("Lot");
                });
#pragma warning restore 612, 618
        }
    }
}
